services:
  devops:
    build: .
    image: devops:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI:=mongodb://mongo:mongo@mongo-server:27017/devopsDb?authSource=admin
    networks:
      - devopsNet

networks:
  devopsNet:
    external: true

#> docker compose up --build -d